name: Publish
on:
  push:
    branches:
      - "main"

# this prevents multiple workflows from running concurrently.
concurrency: $${{ github.workflow }}-${{ github.ref}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install --frozen-lockfile
      - run: npm run lint
      - run: npm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: npm publish